### ISSUE TITLE
Cannot run commands from console

### ISSUE THREAD

**Issue by lhleonardo** [Chocorean/authmod#42]
Hi. First of all, congratulations on creating this mod!

I cannot run commands on my server GUI after installing the mod.

I usually use the interface offered by my server hosting, via the web, and the message "A player is required to execute this command here" always appears.

Here are screenshots showing more about the problem. In this example I used basic Minecraft commands, like seeds, gamemode and stop.

Did you know about this problem?

Tks.

Minecraft Version: 1.16.5

![issue authmod](https://user-images.githubusercontent.com/11544276/127062884-dd2ce37b-7a57-4d48-bca8-d7f1fe925948.gif)

**Comment by lhleonardo** [comment]
Sorry. I forgot to comment out my settings.

My configuration file is:

```toml
#Server configuration settings
[server]
	#Enable or disable the /login command. If disabled, the server will be opened to everyone).
	enableLogin = true
	#delay in seconds a player can authenticate before being automatically kicked from the server.
	#Range: 1 ~ 1024
	delay = 120
	#lang file to use
	#Allowed Values: EN_US, FR_FR, ES_ES
	language = "EN_US"
	#Whitelisted commands (can be used without being logged)
	whitelist = ["register", "login", "logged", "help"]
	#Enable or disable the /register command.
	enableRegister = true
	#Enable or disable the /changepassword command.
	enableChangePassword = true
	#The way you want to store player's data, choose between 'database' or 'file'. If the strategy is unknown, the server will be open for everyone.
	#Allowed Values: FILE, DATABASE
	dataSource = "DATABASE"

[Database]
	#Column name of UUID
	columnUuid = "uuid"
	#Column name of USERNAME
	columnUsername = "username"
	#Column name of BANNED
	columnBanned = "banned"
	#Name of the database
	database = "mydatabase"
	#Database users's password
	password = "mypassword"
	#SQL dialect
	dialect = "mariadb"
	#JDBC driver to use
	driver = "org.mariadb.jdbc.Driver"
	#Port to be used
	#Range: 1024 ~ 65535
	port = "myport"
	#Server hosting the database
	host = "myhost"
	#Column name of PASSWORD
	columnPassword = "password"
	#Database user
	user = "myuser"
	#Table to be used
	table = "players"

```
